name:                daimust
version:             0.1.0.0
github:              kayhide/daimust
license:             BSD3
author:              kayhide
maintainer:          kayhide@gmail.com
copyright:           2018 kayhide

extra-source-files:
  - README.md

dependencies:
  - QuickCheck
  - ansi-terminal
  - async
  - base
  - binary
  - bytestring
  - classy-prelude
  - containers
  - data-default
  - deepseq
  - directory
  - exceptions
  - extensible
  - filepath
  - formatting
  - html-conduit
  - http-client
  - http-client-tls
  - lens
  - lens-datetime
  - megaparsec
  - monad-logger
  - mtl
  - network-uri
  - operational
  - optparse-applicative
  - path
  - path-io
  - prettyprinter
  - prettyprinter-ansi-terminal
  - primitive
  - split
  - stm
  - text
  - time
  - transformers
  - typed-process
  - unliftio
  - unliftio-core
  - unordered-containers
  - vector
  - wreq
  - xml-conduit
  - xml-lens

default-extensions:
  - AutoDeriveTypeable
  - BangPatterns
  - BinaryLiterals
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DoAndIfThenElse
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedLists
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - TypeSynonymInstances
  - ViewPatterns

library:
  source-dirs: src

executables:
  daimust:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -optP-Wno-nonportable-include-path
    dependencies:
      - daimust

tests:
  tasty:
    main: Main.hs
    source-dirs: test/tasty
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - daimust
      - tasty
      - tasty-hunit
      - tasty-quickcheck
